import { neon } from "@neondatabase/serverless";

const WINES = [
  {"id": 1, "product_id": "1101601", "name": "Château Léoville-Barton 2015", "producer": "Château Léoville-Barton", "country": "Frankrike", "region": "Bordeaux", "sub_region": "Saint-Julien", "year": 2015, "type": "Rødvin", "grapes": "Cabernet Sauvignon, Merlot", "alcohol": 13.5, "volume": 0.75, "price": 699, "rating": 97, "color": "Dyp rubinrød", "flavor_profile": "Fyldig og strukturert", "taste_fullness": 10, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 10, "taste_bitterness": 4, "aromas": ["svartsrips", "sjokolade", "seder", "laurbær", "tobakk"], "description_no": "En av Bordeaux' store klassikere. Strukturert og lagringsdyktig med dype tanniner og lang ettersmak av mørke bær og seder.", "description_en": "One of Bordeaux's great classics. Structured and age-worthy with deep tannins and a long finish of dark berries and cedar.", "is_eco": false, "is_vegan": false},
  {"id": 2, "product_id": "3000101", "name": "Gevrey-Chambertin 2020", "producer": "Louis Jadot", "country": "Frankrike", "region": "Burgund", "sub_region": "Côte de Nuits", "year": 2020, "type": "Rødvin", "grapes": "Pinot Noir", "alcohol": 13.0, "volume": 0.75, "price": 449, "rating": 92, "color": "Lys rubinrød", "flavor_profile": "Elegant og fruktig", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["kirsebær", "bringebær", "viol", "jord", "sopp"], "description_no": "Elegant burgunder med klassisk jordbær- og kirsebærfrukt, friske tanniner og god syrlighet. Typisk Côte de Nuits-karakter.", "description_en": "Elegant Burgundy with classic strawberry and cherry fruit, fresh tannins and good acidity. Typical Côte de Nuits character.", "is_eco": false, "is_vegan": true},
  {"id": 3, "product_id": "3500101", "name": "Châteauneuf-du-Pape 2019", "producer": "Château Rayas", "country": "Frankrike", "region": "Rhône", "sub_region": "Châteauneuf-du-Pape", "year": 2019, "type": "Rødvin", "grapes": "Grenache", "alcohol": 14.5, "volume": 0.75, "price": 1290, "rating": 99, "color": "Mellomrød", "flavor_profile": "Kompleks og konsentrert", "taste_fullness": 10, "taste_sweetness": 3, "taste_freshness": 7, "taste_tannins": 6, "taste_bitterness": 3, "aromas": ["kirsebær", "lavendel", "pepper", "lakriss", "krydder"], "description_no": "Legendarisk grenache fra Châteauneuf-du-Pape. Unik kompleksitet med rød frukt, lavendel og krydder. Blant Rhônes aller beste.", "description_en": "Legendary grenache from Châteauneuf-du-Pape. Unique complexity with red fruit, lavender and spice. Among Rhône's very finest.", "is_eco": false, "is_vegan": false},
  {"id": 4, "product_id": "4500101", "name": "Crozes-Hermitage Rouge 2021", "producer": "M. Chapoutier", "country": "Frankrike", "region": "Rhône", "sub_region": "Crozes-Hermitage", "year": 2021, "type": "Rødvin", "grapes": "Syrah", "alcohol": 13.5, "volume": 0.75, "price": 219, "rating": 90, "color": "Dyp lilla", "flavor_profile": "Kraftig og krydret", "taste_fullness": 9, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 8, "taste_bitterness": 4, "aromas": ["blåbær", "pepper", "lakriss", "oliven", "røyk"], "description_no": "Klassisk nordre Rhône syrah med markant pepper og mørk frukt. God hverdagsvin med typisk Crozes-Hermitage-preg.", "description_en": "Classic northern Rhône syrah with pronounced pepper and dark fruit. A good everyday wine with typical Crozes-Hermitage character.", "is_eco": true, "is_vegan": true},
  {"id": 5, "product_id": "5000201", "name": "Saint-Émilion Grand Cru 2018", "producer": "Château Figeac", "country": "Frankrike", "region": "Bordeaux", "sub_region": "Saint-Émilion", "year": 2018, "type": "Rødvin", "grapes": "Merlot, Cabernet Franc, Cabernet Sauvignon", "alcohol": 14.0, "volume": 0.75, "price": 899, "rating": 96, "color": "Dyp rubinrød", "flavor_profile": "Elegant og kompleks", "taste_fullness": 9, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 8, "taste_bitterness": 3, "aromas": ["plomme", "sjokolade", "viol", "tobakk", "seder"], "description_no": "Enestående Saint-Émilion med typisk merlot-bløthet og cabernet-struktur. Dyp og kompleks med lang lagringspotensial.", "description_en": "Outstanding Saint-Émilion with typical merlot softness and cabernet structure. Deep and complex with long ageing potential.", "is_eco": false, "is_vegan": false},
  {"id": 6, "product_id": "5100101", "name": "Fleurie 2022", "producer": "Georges Duboeuf", "country": "Frankrike", "region": "Burgund", "sub_region": "Beaujolais", "year": 2022, "type": "Rødvin", "grapes": "Gamay", "alcohol": 12.5, "volume": 0.75, "price": 179, "rating": 88, "color": "Lys rubinrød", "flavor_profile": "Lett og blomstret", "taste_fullness": 5, "taste_sweetness": 2, "taste_freshness": 10, "taste_tannins": 4, "taste_bitterness": 2, "aromas": ["jordbær", "bringebær", "fiol", "rose", "kirsebær"], "description_no": "Frisk og blomstret beaujolais fra Fleurie-crus. Saftig rød frukt og silkemyke tanniner. Perfekt litt avkjølt til lett kjøtt.", "description_en": "Fresh and floral Beaujolais from the Fleurie cru. Juicy red fruit and silky tannins. Perfect slightly chilled with light meat.", "is_eco": false, "is_vegan": true},
  {"id": 7, "product_id": "6000101", "name": "Pommard 1er Cru Les Rugiens 2018", "producer": "Domaine de Montille", "country": "Frankrike", "region": "Burgund", "sub_region": "Côte de Beaune", "year": 2018, "type": "Rødvin", "grapes": "Pinot Noir", "alcohol": 13.0, "volume": 0.75, "price": 895, "rating": 95, "color": "Mellomrød", "flavor_profile": "Kraftig og strukturert burgunder", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 9, "taste_bitterness": 3, "aromas": ["svartsrips", "sjokolade", "laurbær", "vilt", "sopp"], "description_no": "Kraftig og strukturert burgunder fra den berømte Les Rugiens-vingården. Rik med dype tanniner og lang ettersmak.", "description_en": "Powerful and structured Burgundy from the famous Les Rugiens vineyard. Rich with deep tannins and long finish.", "is_eco": false, "is_vegan": false},
  {"id": 8, "product_id": "6100101", "name": "Corbières Rouge 2021", "producer": "Domaine du Vieux Parc", "country": "Frankrike", "region": "Languedoc-Roussillon", "sub_region": "Corbières", "year": 2021, "type": "Rødvin", "grapes": "Carignan, Grenache, Syrah", "alcohol": 14.0, "volume": 0.75, "price": 119, "rating": 87, "color": "Mørk rubinrød", "flavor_profile": "Fyldig og krydret", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["plomme", "krydder", "lakriss", "pepper", "leire"], "description_no": "Solid hverdagsrødvin fra Corbières med typisk sørlansk fylde og krydder. God valuta for pengene.", "description_en": "Solid everyday red from Corbières with typical southern richness and spice. Excellent value for money.", "is_eco": false, "is_vegan": false},
  {"id": 9, "product_id": "7000101", "name": "Barolo Serralunga d'Alba 2018", "producer": "Fontanafredda", "country": "Italia", "region": "Piemonte", "sub_region": "Barolo", "year": 2018, "type": "Rødvin", "grapes": "Nebbiolo", "alcohol": 14.0, "volume": 0.75, "price": 349, "rating": 93, "color": "Granatfarge", "flavor_profile": "Kraftig og tanninrik", "taste_fullness": 10, "taste_sweetness": 1, "taste_freshness": 8, "taste_tannins": 12, "taste_bitterness": 5, "aromas": ["tjære", "roser", "kirsebær", "tobakk", "lakriss"], "description_no": "Klassisk Barolo med den karakteristiske tjære-og-roser-noten. Kraftige tanniner og lang ettersmak. Krev lagring eller lufting.", "description_en": "Classic Barolo with the characteristic tar and roses note. Powerful tannins and long finish. Requires ageing or decanting.", "is_eco": false, "is_vegan": false},
  {"id": 10, "product_id": "7100101", "name": "Amarone della Valpolicella Classico 2017", "producer": "Allegrini", "country": "Italia", "region": "Veneto", "sub_region": "Valpolicella Classico", "year": 2017, "type": "Rødvin", "grapes": "Corvina, Rondinella, Molinara", "alcohol": 15.5, "volume": 0.75, "price": 449, "rating": 95, "color": "Dyp rubinrød", "flavor_profile": "Intens og konsentrert", "taste_fullness": 12, "taste_sweetness": 3, "taste_freshness": 6, "taste_tannins": 10, "taste_bitterness": 4, "aromas": ["tørket frukt", "sjokolade", "fiken", "krydder", "lakriss"], "description_no": "Majestetisk Amarone laget av halvtørkede druer. Enorm konsentrasjon og kompleksitet med tørket frukt og sjokolade.", "description_en": "Majestic Amarone made from semi-dried grapes. Enormous concentration and complexity with dried fruit and chocolate.", "is_eco": false, "is_vegan": false},
  {"id": 11, "product_id": "7200101", "name": "Chianti Classico Gran Selezione 2018", "producer": "Castello di Ama", "country": "Italia", "region": "Toscana", "sub_region": "Chianti Classico", "year": 2018, "type": "Rødvin", "grapes": "Sangiovese", "alcohol": 13.5, "volume": 0.75, "price": 399, "rating": 95, "color": "Rubinrød", "flavor_profile": "Elegant og strukturert", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 9, "taste_bitterness": 4, "aromas": ["kirsebær", "viol", "tobakk", "laurbær", "jord"], "description_no": "Toppen av Chianti Classico-pyramiden. Ekstraordinær dybde og finesse med typisk sangiovese-friskhet og lang ettersmak.", "description_en": "The pinnacle of the Chianti Classico pyramid. Extraordinary depth and finesse with typical Sangiovese freshness and long finish.", "is_eco": true, "is_vegan": true},
  {"id": 12, "product_id": "7300101", "name": "Brunello di Montalcino 2017", "producer": "Biondi-Santi", "country": "Italia", "region": "Toscana", "sub_region": "Montalcino", "year": 2017, "type": "Rødvin", "grapes": "Sangiovese Grosso", "alcohol": 14.0, "volume": 0.75, "price": 1290, "rating": 98, "color": "Granatfarge", "flavor_profile": "Majestetisk og lagringsdyktig", "taste_fullness": 10, "taste_sweetness": 1, "taste_freshness": 9, "taste_tannins": 11, "taste_bitterness": 4, "aromas": ["kirsebær", "roser", "tobakk", "lær", "jord"], "description_no": "Den legendariske Biondi-Santi Brunello. Enestående lagringspotensial og kompleksitet. Et av Italias aller største viner.", "description_en": "The legendary Biondi-Santi Brunello. Outstanding ageing potential and complexity. One of Italy's very greatest wines.", "is_eco": false, "is_vegan": false},
  {"id": 13, "product_id": "7400101", "name": "Barbaresco 2019", "producer": "Gaja", "country": "Italia", "region": "Piemonte", "sub_region": "Barbaresco", "year": 2019, "type": "Rødvin", "grapes": "Nebbiolo", "alcohol": 14.0, "volume": 0.75, "price": 995, "rating": 97, "color": "Granatfarge", "flavor_profile": "Elegant og kompleks", "taste_fullness": 9, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 10, "taste_bitterness": 4, "aromas": ["roser", "kirsebær", "tobakk", "anis", "viol"], "description_no": "Angelo Gajas ikoniske Barbaresco. Finere og mer elegant enn Barolo med silkemyke tanniner og blomstret eleganse.", "description_en": "Angelo Gaja's iconic Barbaresco. Finer and more elegant than Barolo with silky tannins and floral elegance.", "is_eco": false, "is_vegan": false},
  {"id": 14, "product_id": "7500101", "name": "Ripasso della Valpolicella 2020", "producer": "Zenato", "country": "Italia", "region": "Veneto", "sub_region": "Valpolicella", "year": 2020, "type": "Rødvin", "grapes": "Corvina, Rondinella", "alcohol": 13.5, "volume": 0.75, "price": 199, "rating": 90, "color": "Mørk rubinrød", "flavor_profile": "Fyldig og fruktig", "taste_fullness": 8, "taste_sweetness": 3, "taste_freshness": 7, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["kirsebær", "plomme", "sjokolade", "vanilje", "krydder"], "description_no": "Klassisk Ripasso med ekstra fylde fra kontakt med Amarone-bunnfallet. Saftig mørk frukt og god struktur.", "description_en": "Classic Ripasso with extra richness from contact with Amarone lees. Juicy dark fruit and good structure.", "is_eco": false, "is_vegan": false},
  {"id": 15, "product_id": "7600101", "name": "Primitivo di Manduria 2021", "producer": "Feudi di San Gregorio", "country": "Italia", "region": "Puglia", "sub_region": "Manduria", "year": 2021, "type": "Rødvin", "grapes": "Primitivo", "alcohol": 14.5, "volume": 0.75, "price": 189, "rating": 89, "color": "Mørk lilla", "flavor_profile": "Kraftig og søtfruktig", "taste_fullness": 10, "taste_sweetness": 4, "taste_freshness": 6, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["bjørnebær", "fiken", "sjokolade", "krydder", "lakriss"], "description_no": "Kraftig og fruktrikt søritaliensk rødvin. Rik på mørk frukt, sjokolade og krydder med varm alkohol.", "description_en": "Powerful and fruit-forward southern Italian red. Rich in dark fruit, chocolate and spice with warm alcohol.", "is_eco": false, "is_vegan": false},
  {"id": 16, "product_id": "7700101", "name": "Nero d'Avola 2022", "producer": "Planeta", "country": "Italia", "region": "Sicilia", "sub_region": "Sicilia", "year": 2022, "type": "Rødvin", "grapes": "Nero d'Avola", "alcohol": 13.5, "volume": 0.75, "price": 159, "rating": 88, "color": "Mørk rubinrød", "flavor_profile": "Fruktig og saftig", "taste_fullness": 8, "taste_sweetness": 3, "taste_freshness": 7, "taste_tannins": 6, "taste_bitterness": 3, "aromas": ["kirsebær", "plomme", "sjokolade", "pepper", "lakriss"], "description_no": "Sicilias signaturdruen på sitt beste. Rik mørk frukt, god fylde og typisk siciliansk varme. Utmerket hverdagsvin.", "description_en": "Sicily's signature grape at its best. Rich dark fruit, good body and typical Sicilian warmth. Excellent everyday wine.", "is_eco": true, "is_vegan": true},
  {"id": 17, "product_id": "8000101", "name": "Rioja Gran Reserva 2015", "producer": "La Rioja Alta", "country": "Spania", "region": "Rioja", "sub_region": "Rioja Alta", "year": 2015, "type": "Rødvin", "grapes": "Tempranillo, Graciano, Mazuelo", "alcohol": 13.5, "volume": 0.75, "price": 329, "rating": 95, "color": "Granatfarge", "flavor_profile": "Elegant og fatpreget", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 8, "taste_bitterness": 3, "aromas": ["kirsebær", "vanilje", "laurbær", "tobakk", "lær"], "description_no": "Klassisk Rioja Gran Reserva med 5 år på fat. Elegant balanse mellom frukt, eikefat og jord. Tidløs spansk klassiker.", "description_en": "Classic Rioja Gran Reserva aged 5 years in oak. Elegant balance between fruit, oak and earth. Timeless Spanish classic.", "is_eco": false, "is_vegan": false},
  {"id": 18, "product_id": "8100101", "name": "Priorat Llicorella 2020", "producer": "Álvaro Palacios", "country": "Spania", "region": "Katalonia", "sub_region": "Priorat", "year": 2020, "type": "Rødvin", "grapes": "Garnacha, Cariñena", "alcohol": 14.5, "volume": 0.75, "price": 299, "rating": 93, "color": "Mørk rubinrød", "flavor_profile": "Konsentrert og mineralsk", "taste_fullness": 10, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 9, "taste_bitterness": 4, "aromas": ["bjørnebær", "mineralsk", "lakriss", "krydder", "stein"], "description_no": "Fra den legendariske Álvaro Palacios. Enorm konsentrasjon fra de skiferrike Priorat-skråningene. Mineralsk og kraftfull.", "description_en": "From the legendary Álvaro Palacios. Enormous concentration from Priorat's slate-rich slopes. Mineral and powerful.", "is_eco": false, "is_vegan": false},
  {"id": 19, "product_id": "8200101", "name": "Ribera del Duero Reserva 2018", "producer": "Vega Sicilia", "country": "Spania", "region": "Castilla y León", "sub_region": "Ribera del Duero", "year": 2018, "type": "Rødvin", "grapes": "Tempranillo, Cabernet Sauvignon", "alcohol": 14.0, "volume": 0.75, "price": 1590, "rating": 99, "color": "Dyp rubinrød", "flavor_profile": "Majestetisk og evig", "taste_fullness": 11, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 11, "taste_bitterness": 4, "aromas": ["svartsrips", "seder", "tobakk", "vanilje", "mineralsk"], "description_no": "Spanias mest prestisjefylte vin. Vega Sicilia Único er et monument — enorm kompleksitet og 100+ år lagringspotensial.", "description_en": "Spain's most prestigious wine. Vega Sicilia Único is a monument — enormous complexity and 100+ year ageing potential.", "is_eco": false, "is_vegan": false},
  {"id": 20, "product_id": "8300101", "name": "Jumilla Monastrell 2022", "producer": "Juan Gil", "country": "Spania", "region": "Murcia", "sub_region": "Jumilla", "year": 2022, "type": "Rødvin", "grapes": "Monastrell", "alcohol": 14.5, "volume": 0.75, "price": 129, "rating": 88, "color": "Mørk lilla", "flavor_profile": "Fyldig og mørk frukt", "taste_fullness": 9, "taste_sweetness": 3, "taste_freshness": 6, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["bjørnebær", "sjokolade", "lakriss", "krydder", "pepper"], "description_no": "Kraftig og fruktrikt monastrell fra Jumilla. Mørk frukt, god fylde og fin krydderpreg. Fantastisk verdi.", "description_en": "Powerful and fruit-forward Monastrell from Jumilla. Dark fruit, good body and lovely spice. Fantastic value.", "is_eco": false, "is_vegan": true},
  {"id": 21, "product_id": "9000101", "name": "Malbec Reserve 2021", "producer": "Achaval Ferrer", "country": "Argentina", "region": "Mendoza", "sub_region": "Luján de Cuyo", "year": 2021, "type": "Rødvin", "grapes": "Malbec", "alcohol": 14.0, "volume": 0.75, "price": 229, "rating": 92, "color": "Mørk lilla", "flavor_profile": "Fyldig og fløyelsmyk", "taste_fullness": 9, "taste_sweetness": 3, "taste_freshness": 7, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["plomme", "bjørnebær", "sjokolade", "vanilje", "viol"], "description_no": "Elegant argentinsk malbec fra de høyereliggende vingårdene i Luján de Cuyo. Fløyelsmyke tanniner og intens mørk frukt.", "description_en": "Elegant Argentine Malbec from the higher-altitude vineyards of Luján de Cuyo. Velvety tannins and intense dark fruit.", "is_eco": false, "is_vegan": false},
  {"id": 22, "product_id": "9100101", "name": "Carménère Gran Reserva 2020", "producer": "Concha y Toro", "country": "Chile", "region": "Maipo Valley", "sub_region": "Peumo", "year": 2020, "type": "Rødvin", "grapes": "Carménère", "alcohol": 13.5, "volume": 0.75, "price": 159, "rating": 90, "color": "Mørk rubinrød", "flavor_profile": "Fruktig med grønne noter", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 7, "taste_bitterness": 4, "aromas": ["plomme", "paprika", "krydder", "sjokolade", "pepper"], "description_no": "Chiles signaturdruen på sitt beste. Typisk grønne urtekrydder kombinert med mørk plommefrukt og god struktur.", "description_en": "Chile's signature grape at its best. Typical green herbal spice combined with dark plum fruit and good structure.", "is_eco": false, "is_vegan": false},
  {"id": 23, "product_id": "9200101", "name": "Pinot Noir Casablanca Valley 2022", "producer": "Cono Sur", "country": "Chile", "region": "Casablanca Valley", "sub_region": "Casablanca", "year": 2022, "type": "Rødvin", "grapes": "Pinot Noir", "alcohol": 13.0, "volume": 0.75, "price": 149, "rating": 89, "color": "Lys rubinrød", "flavor_profile": "Elegant og fruktig", "taste_fullness": 6, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 5, "taste_bitterness": 2, "aromas": ["jordbær", "kirsebær", "bringebær", "krydder", "blomst"], "description_no": "Frisk chilensk pinot noir fra det kjølige Casablanca Valley. Elegant med rød frukt og god friskhet.", "description_en": "Fresh Chilean Pinot Noir from the cool Casablanca Valley. Elegant with red fruit and good acidity.", "is_eco": true, "is_vegan": true},
  {"id": 24, "product_id": "10000101", "name": "Cabernet Sauvignon Napa Valley 2019", "producer": "Opus One", "country": "USA", "region": "California", "sub_region": "Napa Valley", "year": 2019, "type": "Rødvin", "grapes": "Cabernet Sauvignon, Merlot", "alcohol": 14.5, "volume": 0.75, "price": 2490, "rating": 98, "color": "Dyp rubinrød", "flavor_profile": "Majestetisk og rik", "taste_fullness": 11, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 10, "taste_bitterness": 3, "aromas": ["svartsrips", "seder", "sjokolade", "laurbær", "tobakk"], "description_no": "Opus One er en av verdens største viner — et Mondavi/Rothschild-samarbeid. Enorm dybde og perfekt balanse.", "description_en": "Opus One is one of the world's greatest wines — a Mondavi/Rothschild collaboration. Enormous depth and perfect balance.", "is_eco": false, "is_vegan": false},
  {"id": 25, "product_id": "10100101", "name": "Shiraz Barossa Valley 2020", "producer": "Penfolds", "country": "Australia", "region": "South Australia", "sub_region": "Barossa Valley", "year": 2020, "type": "Rødvin", "grapes": "Shiraz", "alcohol": 14.5, "volume": 0.75, "price": 189, "rating": 91, "color": "Dyp lilla", "flavor_profile": "Kraftig og røkt", "taste_fullness": 10, "taste_sweetness": 3, "taste_freshness": 6, "taste_tannins": 8, "taste_bitterness": 3, "aromas": ["bjørnebær", "pepper", "røyk", "sjokolade", "lakriss"], "description_no": "Penfolds klassiske Barossa shiraz. Kraftfull og konsentrert med typisk australsk pepper, røyk og mørk frukt.", "description_en": "Penfolds classic Barossa Shiraz. Powerful and concentrated with typical Australian pepper, smoke and dark fruit.", "is_eco": false, "is_vegan": false},
  {"id": 26, "product_id": "10200101", "name": "Pinot Noir Willamette Valley 2020", "producer": "Domaine Drouhin Oregon", "country": "USA", "region": "Oregon", "sub_region": "Willamette Valley", "year": 2020, "type": "Rødvin", "grapes": "Pinot Noir", "alcohol": 13.0, "volume": 0.75, "price": 329, "rating": 93, "color": "Lys rubinrød", "flavor_profile": "Elegant og burgunderinspirert", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 6, "taste_bitterness": 2, "aromas": ["kirsebær", "bringebær", "jord", "krydder", "blomst"], "description_no": "Burgundiernes Oregon-eventyr. Elegant og frisk med typisk burgunder-DNA overført til den nye verden.", "description_en": "The Burgundians' Oregon adventure. Elegant and fresh with typical Burgundy DNA transferred to the New World.", "is_eco": false, "is_vegan": false},
  {"id": 27, "product_id": "11000101", "name": "Chablis Premier Cru Montée de Tonnerre 2021", "producer": "William Fèvre", "country": "Frankrike", "region": "Burgund", "sub_region": "Chablis", "year": 2021, "type": "Hvitvin", "grapes": "Chardonnay", "alcohol": 13.0, "volume": 0.75, "price": 349, "rating": 94, "color": "Lys gyllen", "flavor_profile": "Mineralsk og frisk", "taste_fullness": 7, "taste_sweetness": 1, "taste_freshness": 11, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "grønt eple", "mineralsk", "flint", "blomst"], "description_no": "Quintessential Chablis fra den berømte Montée de Tonnerre-leirhagen. Intens mineralitet og knivskarp friskhet.", "description_en": "Quintessential Chablis from the famous Montée de Tonnerre clay hillside. Intense minerality and razor-sharp freshness.", "is_eco": true, "is_vegan": true},
  {"id": 28, "product_id": "11100101", "name": "Meursault 2020", "producer": "Domaine Leflaive", "country": "Frankrike", "region": "Burgund", "sub_region": "Côte de Beaune", "year": 2020, "type": "Hvitvin", "grapes": "Chardonnay", "alcohol": 13.5, "volume": 0.75, "price": 695, "rating": 96, "color": "Gyllen", "flavor_profile": "Kremete og kompleks", "taste_fullness": 9, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["fersken", "smør", "hasselnøtt", "vanilje", "blomst"], "description_no": "Stor hvit burgunder fra Leflaive. Kremete og fylt med dybde, men med friskhet som holder det elegant og levende.", "description_en": "Great white Burgundy from Leflaive. Creamy and full of depth, yet with freshness that keeps it elegant and vibrant.", "is_eco": true, "is_vegan": true},
  {"id": 29, "product_id": "11200101", "name": "Pouilly-Fumé 2022", "producer": "Didier Dagueneau", "country": "Frankrike", "region": "Loire", "sub_region": "Pouilly-Fumé", "year": 2022, "type": "Hvitvin", "grapes": "Sauvignon Blanc", "alcohol": 13.0, "volume": 0.75, "price": 549, "rating": 96, "color": "Lys gyllen", "flavor_profile": "Intenst mineralsk", "taste_fullness": 7, "taste_sweetness": 1, "taste_freshness": 11, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "stikkelsbær", "røyk", "flint", "blomst"], "description_no": "Den legendariske Didier Dagueneaus Pouilly-Fumé. Intenst mineralsk sauvignon blanc — en av Frankrikes store hvitviner.", "description_en": "The legendary Didier Dagueneau's Pouilly-Fumé. Intensely mineral Sauvignon Blanc — one of France's great white wines.", "is_eco": false, "is_vegan": false},
  {"id": 30, "product_id": "11300101", "name": "Sancerre Blanc 2022", "producer": "Henri Bourgeois", "country": "Frankrike", "region": "Loire", "sub_region": "Sancerre", "year": 2022, "type": "Hvitvin", "grapes": "Sauvignon Blanc", "alcohol": 13.0, "volume": 0.75, "price": 249, "rating": 91, "color": "Lys gyllen", "flavor_profile": "Frisk og urterik", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 11, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["sitrus", "stikkelsbær", "urter", "blomst", "mineralsk"], "description_no": "Klassisk Sancerre med typisk Loire-friskhet og stikkelsbær. Perfekt til sjømat og geitost.", "description_en": "Classic Sancerre with typical Loire freshness and gooseberry. Perfect with seafood and goat cheese.", "is_eco": false, "is_vegan": false},
  {"id": 31, "product_id": "11400101", "name": "Condrieu 2021", "producer": "Guigal", "country": "Frankrike", "region": "Rhône", "sub_region": "Condrieu", "year": 2021, "type": "Hvitvin", "grapes": "Viognier", "alcohol": 14.0, "volume": 0.75, "price": 399, "rating": 94, "color": "Dyp gyllen", "flavor_profile": "Aromatisk og rik", "taste_fullness": 9, "taste_sweetness": 3, "taste_freshness": 7, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["fersken", "aprikos", "blomst", "viol", "krydder"], "description_no": "Storslått viognier fra Condrieu. Enormt aromatisk med fersken, aprikos og viol. Rik og oljeaktig tekstur.", "description_en": "Magnificent Viognier from Condrieu. Enormously aromatic with peach, apricot and violet. Rich and oily texture.", "is_eco": false, "is_vegan": false},
  {"id": 32, "product_id": "11500101", "name": "Alsace Riesling Grand Cru Schlossberg 2020", "producer": "Domaine Weinbach", "country": "Frankrike", "region": "Alsace", "sub_region": "Kaysersberg", "year": 2020, "type": "Hvitvin", "grapes": "Riesling", "alcohol": 13.0, "volume": 0.75, "price": 449, "rating": 95, "color": "Lys gyllen", "flavor_profile": "Mineralsk og frisk riesling", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 11, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "fersken", "mineralsk", "blomst", "honning"], "description_no": "Majestetisk alsasisk riesling fra Grand Cru Schlossberg. Intens mineralitet, friskhet og lagringspotensial.", "description_en": "Majestic Alsatian Riesling from Grand Cru Schlossberg. Intense minerality, freshness and ageing potential.", "is_eco": true, "is_vegan": true},
  {"id": 33, "product_id": "12000101", "name": "Gavi di Gavi DOCG 2022", "producer": "La Scolca", "country": "Italia", "region": "Piemonte", "sub_region": "Gavi", "year": 2022, "type": "Hvitvin", "grapes": "Cortese", "alcohol": 12.0, "volume": 0.75, "price": 189, "rating": 89, "color": "Lys gyllen", "flavor_profile": "Frisk og blomstret", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "grønt eple", "blomst", "mandel", "mineralsk"], "description_no": "Piemontes svar på frisk hvitvin. La Scolca er referansen for Gavi — ren, frisk og elegante med god mineralitet.", "description_en": "Piedmont's answer to fresh white wine. La Scolca is the reference for Gavi — pure, fresh and elegant with good minerality.", "is_eco": false, "is_vegan": false},
  {"id": 34, "product_id": "12100101", "name": "Soave Classico Superiore 2022", "producer": "Pieropan", "country": "Italia", "region": "Veneto", "sub_region": "Soave", "year": 2022, "type": "Hvitvin", "grapes": "Garganega, Trebbiano di Soave", "alcohol": 12.5, "volume": 0.75, "price": 169, "rating": 90, "color": "Lys gyllen", "flavor_profile": "Frisk og mandelduftet", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "mandel", "blomst", "eple", "mineralsk"], "description_no": "Den beste produsenten i Soave. Elegant og frisk med karakteristisk mandel og sitrus. Utmerket til fisk.", "description_en": "The finest producer in Soave. Elegant and fresh with characteristic almond and citrus. Outstanding with fish.", "is_eco": false, "is_vegan": false},
  {"id": 35, "product_id": "12200101", "name": "Albariño Rías Baixas 2022", "producer": "Pazo de Señoráns", "country": "Spania", "region": "Galicia", "sub_region": "Rías Baixas", "year": 2022, "type": "Hvitvin", "grapes": "Albariño", "alcohol": 13.0, "volume": 0.75, "price": 199, "rating": 91, "color": "Lys gyllen", "flavor_profile": "Aromatisk og frisk", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 11, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["fersken", "aprikos", "sitrus", "blomst", "mineralsk"], "description_no": "Galicisk albariño på sitt ypperste. Aromatiisk og frisk med fersken, sitrus og god mineralitet. Perfekt til sjømat.", "description_en": "Galician Albariño at its finest. Aromatic and fresh with peach, citrus and good minerality. Perfect with seafood.", "is_eco": false, "is_vegan": false},
  {"id": 36, "product_id": "12300101", "name": "Verdejo Rueda 2022", "producer": "Marqués de Riscal", "country": "Spania", "region": "Castilla y León", "sub_region": "Rueda", "year": 2022, "type": "Hvitvin", "grapes": "Verdejo", "alcohol": 13.0, "volume": 0.75, "price": 149, "rating": 88, "color": "Lys gyllen", "flavor_profile": "Frisk og urterik", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["sitrus", "urter", "fennikel", "eple", "blomst"], "description_no": "Klassisk spansk hvitvin fra Rueda. Frisk og urterik verdejo med god friskhet og behagelig bitterhet.", "description_en": "Classic Spanish white from Rueda. Fresh and herbal Verdejo with good acidity and pleasant bitterness.", "is_eco": false, "is_vegan": false},
  {"id": 37, "product_id": "13000101", "name": "Riesling Spätlese Mosel 2021", "producer": "Dr. Loosen", "country": "Tyskland", "region": "Mosel", "sub_region": "Bernkastel", "year": 2021, "type": "Hvitvin", "grapes": "Riesling", "alcohol": 8.0, "volume": 0.75, "price": 219, "rating": 92, "color": "Lys gyllen", "flavor_profile": "Halvtørr og mineralsk", "taste_fullness": 6, "taste_sweetness": 5, "taste_freshness": 12, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["sitrus", "fersken", "mineralsk", "skifer", "blomst"], "description_no": "Klassisk Mosel-riesling med den typiske balansen mellom sødme og syrlighet. Skiferpreget mineralitet og lav alkohol.", "description_en": "Classic Mosel Riesling with the typical balance of sweetness and acidity. Slate-driven minerality and low alcohol.", "is_eco": false, "is_vegan": false},
  {"id": 38, "product_id": "13100101", "name": "Grüner Veltliner Smaragd Wachau 2021", "producer": "Domäne Wachau", "country": "Østerrike", "region": "Niederösterreich", "sub_region": "Wachau", "year": 2021, "type": "Hvitvin", "grapes": "Grüner Veltliner", "alcohol": 13.5, "volume": 0.75, "price": 279, "rating": 93, "color": "Lys gyllen", "flavor_profile": "Fyldig og pepperaktig", "taste_fullness": 8, "taste_sweetness": 1, "taste_freshness": 9, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["hvit pepper", "sitrus", "eple", "mineralsk", "blomst"], "description_no": "Wachaus mest prestisjefulle klassifisering. Fyldig og kompleks grüner veltliner med karakteristisk hvit pepper.", "description_en": "Wachau's most prestigious classification. Full-bodied and complex Grüner Veltliner with characteristic white pepper.", "is_eco": true, "is_vegan": true},
  {"id": 39, "product_id": "14000101", "name": "Chardonnay Napa Valley 2020", "producer": "Kistler", "country": "USA", "region": "California", "sub_region": "Napa Valley", "year": 2020, "type": "Hvitvin", "grapes": "Chardonnay", "alcohol": 14.0, "volume": 0.75, "price": 549, "rating": 95, "color": "Dyp gyllen", "flavor_profile": "Rik og kremete", "taste_fullness": 10, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["fersken", "smør", "eik", "vanilje", "hasselnøtt"], "description_no": "Californias svar på hvit Burgund. Rik, kremete og kompleks med typisk Kistler-eleganse og god friskhet.", "description_en": "California's answer to white Burgundy. Rich, creamy and complex with typical Kistler elegance and good freshness.", "is_eco": false, "is_vegan": false},
  {"id": 40, "product_id": "14100101", "name": "Sauvignon Blanc Marlborough 2023", "producer": "Cloudy Bay", "country": "New Zealand", "region": "Marlborough", "sub_region": "Wairau Valley", "year": 2023, "type": "Hvitvin", "grapes": "Sauvignon Blanc", "alcohol": 13.0, "volume": 0.75, "price": 199, "rating": 91, "color": "Lys gyllen", "flavor_profile": "Intenst aromatisk", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 11, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["stikkelsbær", "pasjonsfrukt", "sitrus", "urter", "blomst"], "description_no": "Ikonisk nyzealandsk sauvignon blanc. Eksplosivt aromatisk med pasjonsfrukt, stikkelsbær og frisk syrlighet.", "description_en": "Iconic New Zealand Sauvignon Blanc. Explosively aromatic with passion fruit, gooseberry and fresh acidity.", "is_eco": false, "is_vegan": true},
  {"id": 41, "product_id": "14200101", "name": "Chardonnay Margaret River 2021", "producer": "Leeuwin Estate", "country": "Australia", "region": "Western Australia", "sub_region": "Margaret River", "year": 2021, "type": "Hvitvin", "grapes": "Chardonnay", "alcohol": 13.5, "volume": 0.75, "price": 449, "rating": 95, "color": "Gyllen", "flavor_profile": "Elegant og kompleks", "taste_fullness": 8, "taste_sweetness": 1, "taste_freshness": 9, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["sitrus", "fersken", "eik", "mineralsk", "blomst"], "description_no": "Australias svar på Grand Cru Burgund. Leeuwin Art Series er en av landets aller ypperste hvitviner.", "description_en": "Australia's answer to Grand Cru Burgundy. Leeuwin Art Series is one of the country's finest white wines.", "is_eco": false, "is_vegan": false},
  {"id": 42, "product_id": "15000101", "name": "Provence Rosé 2023", "producer": "Château d'Esclans", "country": "Frankrike", "region": "Provence", "sub_region": "Côtes de Provence", "year": 2023, "type": "Rosévin", "grapes": "Grenache, Rolle, Syrah", "alcohol": 13.0, "volume": 0.75, "price": 219, "rating": 90, "color": "Blek laks", "flavor_profile": "Elegant og tørr rosé", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 9, "taste_tannins": 1, "taste_bitterness": 2, "aromas": ["jordbær", "rose", "sitrus", "fersken", "blomst"], "description_no": "En av Provences beste roséviner. Blek lakserosa og knasende tørr med delikat jordbærfrukt og blomstret eleganse.", "description_en": "One of Provence's finest rosés. Pale salmon pink and bone dry with delicate strawberry fruit and floral elegance.", "is_eco": false, "is_vegan": false},
  {"id": 43, "product_id": "15100101", "name": "Tavel Rosé 2022", "producer": "Château d'Aqueria", "country": "Frankrike", "region": "Rhône", "sub_region": "Tavel", "year": 2022, "type": "Rosévin", "grapes": "Grenache, Cinsault, Clairette", "alcohol": 13.5, "volume": 0.75, "price": 179, "rating": 89, "color": "Mørk rosé", "flavor_profile": "Fyldig og strukturert rosé", "taste_fullness": 7, "taste_sweetness": 1, "taste_freshness": 8, "taste_tannins": 2, "taste_bitterness": 3, "aromas": ["jordbær", "bringebær", "krydder", "blomst", "sitrus"], "description_no": "Frankrike eneste AOC utelukkende for rosé. Fyldigere og mer strukturert enn Provence-rosé. Utmerket til mat.", "description_en": "France's only AOC exclusively for rosé. Fuller and more structured than Provence rosé. Excellent with food.", "is_eco": false, "is_vegan": false},
  {"id": 44, "product_id": "16000101", "name": "Champagne Blanc de Blancs NV", "producer": "Krug", "country": "Frankrike", "region": "Champagne", "sub_region": "Blanc de Blancs", "year": null, "type": "Musserende vin", "grapes": "Chardonnay", "alcohol": 12.0, "volume": 0.75, "price": 1690, "rating": 98, "color": "Lys gyllen", "flavor_profile": "Kompleks og prestisjefylt", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "brioche", "eik", "mineralsk", "blomst"], "description_no": "Krug er champagnehusenes champagnehus. Ekstraordinær kompleksitet og dybde med lang ettersmak. Et monument.", "description_en": "Krug is the champagne house's champagne house. Extraordinary complexity and depth with long finish. A monument.", "is_eco": false, "is_vegan": false},
  {"id": 45, "product_id": "16100101", "name": "Champagne Brut NV", "producer": "Moët & Chandon", "country": "Frankrike", "region": "Champagne", "sub_region": "Epernay", "year": null, "type": "Musserende vin", "grapes": "Pinot Noir, Chardonnay, Pinot Meunier", "alcohol": 12.0, "volume": 0.75, "price": 369, "rating": 89, "color": "Lys gyllen", "flavor_profile": "Fruktig og tilgjengelig", "taste_fullness": 6, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["eple", "sitrus", "brioche", "blomst", "mineralsk"], "description_no": "Verdens mest kjente champagne. Frisk og tilgjengelig med eple, sitrus og lett gjærpreg. Perfekt til feiring.", "description_en": "The world's most famous Champagne. Fresh and approachable with apple, citrus and light yeast. Perfect for celebration.", "is_eco": false, "is_vegan": false},
  {"id": 46, "product_id": "16200101", "name": "Champagne Blanc de Noirs NV", "producer": "Bollinger", "country": "Frankrike", "region": "Champagne", "sub_region": "Ay", "year": null, "type": "Musserende vin", "grapes": "Pinot Noir, Pinot Meunier", "alcohol": 12.0, "volume": 0.75, "price": 599, "rating": 94, "color": "Lys gyllen", "flavor_profile": "Kraftig og strukturert champagne", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 9, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["rød eple", "brioche", "nøtt", "krydder", "blomst"], "description_no": "Bollinger ER champagne for James Bond. Kraftig og strukturert med pinot-dominert karakter og god lagringspotensial.", "description_en": "Bollinger IS the champagne for James Bond. Powerful and structured with Pinot-dominant character and good ageing potential.", "is_eco": false, "is_vegan": false},
  {"id": 47, "product_id": "16300101", "name": "Prosecco Superiore DOCG 2022", "producer": "Bisol", "country": "Italia", "region": "Veneto", "sub_region": "Valdobbiadene", "year": 2022, "type": "Musserende vin", "grapes": "Glera", "alcohol": 11.5, "volume": 0.75, "price": 159, "rating": 88, "color": "Lys gyllen", "flavor_profile": "Lett og blomstret", "taste_fullness": 5, "taste_sweetness": 3, "taste_freshness": 9, "taste_tannins": 0, "taste_bitterness": 1, "aromas": ["eple", "pære", "fersken", "blomst", "sitrus"], "description_no": "Valdobbiadenes beste prosecco. Frisk og blomstret med eple og pære. Perfekt aperitiff.", "description_en": "Valdobbiadene's finest Prosecco. Fresh and floral with apple and pear. Perfect aperitif.", "is_eco": false, "is_vegan": false},
  {"id": 48, "product_id": "16400101", "name": "Cava Brut Nature Gran Reserva 2019", "producer": "Gramona", "country": "Spania", "region": "Katalonia", "sub_region": "Sant Sadurní d'Anoia", "year": 2019, "type": "Musserende vin", "grapes": "Xarel·lo, Macabeo, Parellada", "alcohol": 12.0, "volume": 0.75, "price": 249, "rating": 93, "color": "Lys gyllen", "flavor_profile": "Mineralsk og kompleks cava", "taste_fullness": 7, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "eple", "gjær", "mineralsk", "nøtt"], "description_no": "Gramona lager Spanias mest prestisjefylte cava. Lang autolytisk modning gir kompleksitet på nivå med god champagne.", "description_en": "Gramona makes Spain's most prestigious Cava. Long autolytic ageing gives complexity rivalling good Champagne.", "is_eco": true, "is_vegan": true},
  {"id": 49, "product_id": "17000101", "name": "Sauternes 2015", "producer": "Château d'Yquem", "country": "Frankrike", "region": "Bordeaux", "sub_region": "Sauternes", "year": 2015, "type": "Dessertvin", "grapes": "Sémillon, Sauvignon Blanc", "alcohol": 13.5, "volume": 0.375, "price": 1490, "rating": 100, "color": "Dyp gyllen", "flavor_profile": "Utsøkt søt og kompleks", "taste_fullness": 10, "taste_sweetness": 12, "taste_freshness": 8, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["honning", "aprikos", "safran", "vanilje", "botrytis"], "description_no": "Verdens største dessertvin. Château d'Yquem i 2015 er nesten for perfekt til å drikke — honning, safran og evig ettersmak.", "description_en": "The world's greatest dessert wine. Château d'Yquem 2015 is almost too perfect to drink — honey, saffron and eternal finish.", "is_eco": false, "is_vegan": false},
  {"id": 50, "product_id": "17100101", "name": "Vintage Port 2017", "producer": "Graham's", "country": "Portugal", "region": "Douro", "sub_region": "Cima Corgo", "year": 2017, "type": "Sterkvin", "grapes": "Touriga Nacional, Touriga Franca", "alcohol": 20.0, "volume": 0.75, "price": 399, "rating": 95, "color": "Mørk rubinrød", "flavor_profile": "Rik og søt portvin", "taste_fullness": 11, "taste_sweetness": 10, "taste_freshness": 7, "taste_tannins": 9, "taste_bitterness": 3, "aromas": ["bjørnebær", "sjokolade", "rosin", "krydder", "tobakk"], "description_no": "Graham's legendariske Vintage Port fra det eksepsjonelle 2017-årgangen. Enorm dybde og 50+ år lagringspotensial.", "description_en": "Graham's legendary Vintage Port from the exceptional 2017 vintage. Enormous depth and 50+ year ageing potential.", "is_eco": false, "is_vegan": false},
  {"id": 51, "product_id": "17200101", "name": "Fino Sherry", "producer": "Tío Pepe (González Byass)", "country": "Spania", "region": "Andalucia", "sub_region": "Jerez", "year": null, "type": "Sterkvin", "grapes": "Palomino", "alcohol": 15.0, "volume": 0.75, "price": 149, "rating": 91, "color": "Lys strågul", "flavor_profile": "Tørr og nøtteaktig", "taste_fullness": 5, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 4, "aromas": ["mandel", "gjær", "brød", "sitrus", "salt"], "description_no": "Verdens mest kjente fino sherry. Knasende tørr med karakteristisk gjær og mandel. Drikkes iskald som aperitiff.", "description_en": "The world's most famous Fino Sherry. Bone dry with characteristic yeast and almond. Drink ice cold as aperitif.", "is_eco": false, "is_vegan": false},
  {"id": 52, "product_id": "18000101", "name": "Merlot Pays d'Oc 2022", "producer": "Gérard Bertrand", "country": "Frankrike", "region": "Languedoc-Roussillon", "sub_region": "Pays d'Oc", "year": 2022, "type": "Rødvin", "grapes": "Merlot", "alcohol": 13.0, "volume": 0.75, "price": 119, "rating": 86, "color": "Rubinrød", "flavor_profile": "Myk og fruktig", "taste_fullness": 6, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 5, "taste_bitterness": 2, "aromas": ["plomme", "kirsebær", "vanilje", "urter", "blomst"], "description_no": "Myk og tilgjengelig hverdagsmerlot fra Languedoc. Enkel og behagelig med plomme og kirsebær. God valuta.", "description_en": "Soft and approachable everyday Merlot from Languedoc. Simple and pleasant with plum and cherry. Good value.", "is_eco": false, "is_vegan": false},
  {"id": 53, "product_id": "18100101", "name": "Pinot Grigio delle Venezie 2023", "producer": "Santa Margherita", "country": "Italia", "region": "Veneto", "sub_region": "Venezie", "year": 2023, "type": "Hvitvin", "grapes": "Pinot Grigio", "alcohol": 12.0, "volume": 0.75, "price": 159, "rating": 85, "color": "Lys gyllen", "flavor_profile": "Lett og frisk", "taste_fullness": 5, "taste_sweetness": 1, "taste_freshness": 9, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["eple", "sitrus", "blomst", "mineralsk", "pære"], "description_no": "Det originale Santa Margherita pinot grigio — den som startet trenden. Frisk, lett og alltid pålitelig.", "description_en": "The original Santa Margherita Pinot Grigio — the one that started the trend. Fresh, light and always reliable.", "is_eco": false, "is_vegan": false},
  {"id": 54, "product_id": "18200101", "name": "Côtes du Rhône Rouge 2022", "producer": "Guigal", "country": "Frankrike", "region": "Rhône", "sub_region": "Côtes du Rhône", "year": 2022, "type": "Rødvin", "grapes": "Grenache, Syrah, Mourvèdre", "alcohol": 13.5, "volume": 0.75, "price": 139, "rating": 88, "color": "Mørk rubinrød", "flavor_profile": "Fruktig og krydret", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 6, "taste_bitterness": 3, "aromas": ["kirsebær", "pepper", "krydder", "lakriss", "urter"], "description_no": "Guigals klassiske Côtes du Rhône er referansen i sin klasse. Konsistent og pålitelig med typisk Rhône-karakter.", "description_en": "Guigal's classic Côtes du Rhône is the reference in its class. Consistent and reliable with typical Rhône character.", "is_eco": false, "is_vegan": false},
  {"id": 55, "product_id": "18300101", "name": "Malbec Reserva Mendoza 2022", "producer": "Zuccardi", "country": "Argentina", "region": "Mendoza", "sub_region": "Valle de Uco", "year": 2022, "type": "Rødvin", "grapes": "Malbec", "alcohol": 14.0, "volume": 0.75, "price": 149, "rating": 90, "color": "Mørk lilla", "flavor_profile": "Fyldig og fruktig", "taste_fullness": 8, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 7, "taste_bitterness": 3, "aromas": ["bjørnebær", "viol", "plomme", "sjokolade", "krydder"], "description_no": "Zuccardi er Argentinas beste produsent. Denne malbecen viser Valle de Ucos eleganse og friskhet.", "description_en": "Zuccardi is Argentina's finest producer. This Malbec shows Valle de Uco's elegance and freshness.", "is_eco": false, "is_vegan": false},
  {"id": 56, "product_id": "18400101", "name": "Cabernet Sauvignon Central Valley 2022", "producer": "Concha y Toro Casillero del Diablo", "country": "Chile", "region": "Central Valley", "sub_region": "Maipo Valley", "year": 2022, "type": "Rødvin", "grapes": "Cabernet Sauvignon", "alcohol": 13.5, "volume": 0.75, "price": 99, "rating": 85, "color": "Mørk rubinrød", "flavor_profile": "Fruktig og tilgjengelig", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 7, "taste_tannins": 6, "taste_bitterness": 3, "aromas": ["svartsrips", "plomme", "vanilje", "urter", "pepper"], "description_no": "Den ikoniske Casillero del Diablo — en av verdens mest solgte viner. Pålitelig og god til prisen.", "description_en": "The iconic Casillero del Diablo — one of the world's best-selling wines. Reliable and good for the price.", "is_eco": false, "is_vegan": false},
  {"id": 57, "product_id": "18500101", "name": "Sauvignon Blanc Western Cape 2023", "producer": "Ken Forrester", "country": "Sør-Afrika", "region": "Western Cape", "sub_region": "Stellenbosch", "year": 2023, "type": "Hvitvin", "grapes": "Sauvignon Blanc", "alcohol": 13.0, "volume": 0.75, "price": 129, "rating": 87, "color": "Lys gyllen", "flavor_profile": "Frisk og fruktig", "taste_fullness": 6, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["sitrus", "stikkelsbær", "urter", "blomst", "fersken"], "description_no": "Frisk og aromatisk sørafrikansk sauvignon blanc. God hverdagsvin med typisk Cape-friskhet.", "description_en": "Fresh and aromatic South African Sauvignon Blanc. Good everyday wine with typical Cape freshness.", "is_eco": false, "is_vegan": false},
  {"id": 58, "product_id": "18600101", "name": "Tempranillo Rioja Joven 2022", "producer": "Muga", "country": "Spania", "region": "Rioja", "sub_region": "Rioja Alta", "year": 2022, "type": "Rødvin", "grapes": "Tempranillo, Garnacha, Mazuelo", "alcohol": 13.5, "volume": 0.75, "price": 149, "rating": 89, "color": "Rubinrød", "flavor_profile": "Fruktig og upretensiøs", "taste_fullness": 7, "taste_sweetness": 2, "taste_freshness": 8, "taste_tannins": 6, "taste_bitterness": 3, "aromas": ["kirsebær", "jordbær", "laurbær", "urter", "vanilje"], "description_no": "Mugas inngangsnivå er bevis på at god Rioja ikke trenger å koste mye. Frisk og saftig med rød frukt.", "description_en": "Muga's entry level is proof that good Rioja doesn't need to cost much. Fresh and juicy with red fruit.", "is_eco": false, "is_vegan": false},
  {"id": 59, "product_id": "18700101", "name": "Riesling Rheingau Kabinett 2022", "producer": "Schloss Johannisberg", "country": "Tyskland", "region": "Rheingau", "sub_region": "Johannisberg", "year": 2022, "type": "Hvitvin", "grapes": "Riesling", "alcohol": 9.0, "volume": 0.75, "price": 189, "rating": 90, "color": "Lys gyllen", "flavor_profile": "Halvtørr og frisk", "taste_fullness": 5, "taste_sweetness": 4, "taste_freshness": 12, "taste_tannins": 0, "taste_bitterness": 2, "aromas": ["sitrus", "fersken", "mineralsk", "blomst", "eple"], "description_no": "Schloss Johannisberg er rieslingens hjemsted. Klassisk Rheingau-kabinett med fin balanse mellom sødme og syre.", "description_en": "Schloss Johannisberg is the home of Riesling. Classic Rheingau Kabinett with fine balance between sweetness and acidity.", "is_eco": false, "is_vegan": false},
  {"id": 60, "product_id": "18800101", "name": "Verdejo Rueda Joven 2023", "producer": "Belondrade y Lurton", "country": "Spania", "region": "Castilla y León", "sub_region": "Rueda", "year": 2023, "type": "Hvitvin", "grapes": "Verdejo", "alcohol": 13.0, "volume": 0.75, "price": 229, "rating": 91, "color": "Lys gyllen", "flavor_profile": "Kompleks og frisk", "taste_fullness": 7, "taste_sweetness": 1, "taste_freshness": 10, "taste_tannins": 0, "taste_bitterness": 3, "aromas": ["sitrus", "fennikel", "urter", "blomst", "mineralsk"], "description_no": "Ruedas beste produsent. Kompleks og frisk verdejo med typisk fennikel og urtepreg. Utmerket til sjømat.", "description_en": "Rueda's finest producer. Complex and fresh Verdejo with typical fennel and herbal notes. Excellent with seafood.", "is_eco": false, "is_vegan": false},
];

export default async function handler(req, res) {
  const sql = neon(process.env.DATABASE_URL);

  await sql`
    CREATE TABLE IF NOT EXISTS vb_wines (
      id INTEGER PRIMARY KEY,
      product_id TEXT,
      name TEXT NOT NULL,
      producer TEXT,
      country TEXT,
      region TEXT,
      sub_region TEXT,
      year INTEGER,
      type TEXT,
      grapes TEXT,
      alcohol REAL,
      volume REAL,
      price INTEGER,
      rating INTEGER,
      color TEXT,
      flavor_profile TEXT,
      taste_fullness INTEGER,
      taste_sweetness INTEGER,
      taste_freshness INTEGER,
      taste_tannins INTEGER,
      taste_bitterness INTEGER,
      aromas TEXT DEFAULT '[]',
      description_no TEXT,
      description_en TEXT,
      is_eco BOOLEAN DEFAULT false,
      is_vegan BOOLEAN DEFAULT false
    )
  `;

  let inserted = 0;
  for (const w of WINES) {
    await sql`
      INSERT INTO vb_wines (
        id, product_id, name, producer, country, region, sub_region, year, type,
        grapes, alcohol, volume, price, rating, color, flavor_profile,
        taste_fullness, taste_sweetness, taste_freshness, taste_tannins, taste_bitterness,
        aromas, description_no, description_en, is_eco, is_vegan
      ) VALUES (
        ${w.id}, ${w.product_id}, ${w.name}, ${w.producer}, ${w.country},
        ${w.region}, ${w.sub_region}, ${w.year ?? null}, ${w.type}, ${w.grapes},
        ${w.alcohol}, ${w.volume}, ${w.price}, ${w.rating}, ${w.color},
        ${w.flavor_profile}, ${w.taste_fullness}, ${w.taste_sweetness},
        ${w.taste_freshness}, ${w.taste_tannins}, ${w.taste_bitterness},
        ${JSON.stringify(w.aromas)}, ${w.description_no}, ${w.description_en},
        ${w.is_eco}, ${w.is_vegan}
      )
      ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name, producer = EXCLUDED.producer,
        country = EXCLUDED.country, region = EXCLUDED.region,
        sub_region = EXCLUDED.sub_region, year = EXCLUDED.year,
        type = EXCLUDED.type, grapes = EXCLUDED.grapes,
        alcohol = EXCLUDED.alcohol, volume = EXCLUDED.volume,
        price = EXCLUDED.price, rating = EXCLUDED.rating,
        color = EXCLUDED.color, flavor_profile = EXCLUDED.flavor_profile,
        taste_fullness = EXCLUDED.taste_fullness,
        taste_sweetness = EXCLUDED.taste_sweetness,
        taste_freshness = EXCLUDED.taste_freshness,
        taste_tannins = EXCLUDED.taste_tannins,
        taste_bitterness = EXCLUDED.taste_bitterness,
        aromas = EXCLUDED.aromas,
        description_no = EXCLUDED.description_no,
        description_en = EXCLUDED.description_en,
        is_eco = EXCLUDED.is_eco, is_vegan = EXCLUDED.is_vegan
    `;
    inserted++;
  }

  return res.status(200).json({ ok: true, inserted, message: `Seeded ${inserted} wines.` });
}
